services:
  - type: web
    name: itachi-xmd-v2
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: itachi-sessions
      mountPath: /app/sessions
      sizeGB: 1


